WITH DateSeries AS
(
SELECT CAST('2023-01-01' AS DATE) AS MyDate

UNION ALL

SELECT 
DATEADD(DAY,1,MyDate)
FROM DateSeries
WHERE MyDate <  CAST('2023-12-31' AS DATE)

)


SELECT MyDate
FROM DateSeries
OPTION(MAXRECURSION 365)